platform :ios, '7.0'
pod 'AFNetworking'
pod 'CocoaLumberjack'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'FMDB'
pod 'PureLayout'
pod 'ReactiveCocoa'
pod 'ReactiveViewModel'
pod 'MJExtension'
pod 'MMDrawerController', '~> 0.6.0'
pod 'TPKeyboardAvoiding'
pod 'HHRouter', '~> 0.1.5'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'UITableView+FDTemplateLayoutCell'
pod 'SDWebImage-Category', '1.4'
pod 'AFNetworking-RACExtensions', :git => 'https://github.com/knshiro/AFNetworking-RACExtensions.git'

target :JianDanTests, :exclusive => true do
 pod 'Kiwi','~> 2.4.0'
end